# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x06llm.v1\"h\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_p\x18\x04 \x01(\x02\x12\r\n\x05top_k\x18\x05 \x01(\x05\"\x1d\n\rGenerateReply\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x05Token\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\x32}\n\x03LLM\x12:\n\x08Generate\x12\x17.llm.v1.GenerateRequest\x1a\x15.llm.v1.GenerateReply\x12:\n\x0eStreamGenerate\x12\x17.llm.v1.GenerateRequest\x1a\r.llm.v1.Token0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=21
  _globals['_GENERATEREQUEST']._serialized_end=125
  _globals['_GENERATEREPLY']._serialized_start=127
  _globals['_GENERATEREPLY']._serialized_end=156
  _globals['_TOKEN']._serialized_start=158
  _globals['_TOKEN']._serialized_end=196
  _globals['_LLM']._serialized_start=198
  _globals['_LLM']._serialized_end=323
# @@protoc_insertion_point(module_scope)